name: playwright_workspace
publish_to: none

environment:
  sdk: ^3.6.2

workspace:
  - packages/playwright_protocol
  - packages/playwright_core
  - packages/playwright
  - packages/playwright_mcp
dev_dependencies:
  playwright: any
  ffi: any
dependencies:
  win32: ^5.10.1
