name: playwright_workspace
publish_to: none

environment:
  sdk: ^3.6.2

workspace:
  - packages/playwright_protocol
  - packages/playwright_core
  - packages/playwright
dev_dependencies:
  playwright: any
